SITE_TITLE: Engineer Site
HOME_URL: '/'
SITE_URL: http://localhost:8080

POST_DIR:
  - posts
  - archives

POST_TIMEZONE: 'America/Los_Angeles'

PUBLISH_DRAFTS: no

THEME_SETTINGS:
  typekit_id: lvr3vky

PREPROCESS_LESS: no
DEBUG: no

THEME: oleb
